const fs=require('fs');
const file='dist/app.js';let js=fs.readFileSync(file,'utf8');
const start=js.indexOf('function begin('),end=js.indexOf('function draw(');
js=js.slice(0,start)+`
function lineEquation(m,b){let term=m===0?'':(m===1?'':m===-1?'−':frac(m))+'x';if(b!==0)term+=(term?(b<0?' − ':' + '):(b<0?'−':''))+frac(Math.abs(b));return 'y = '+(term||'0');}
function makeQuestion(a,p,q,r,pair){const [name,u,v,letters]=[['AB',p,q,['p','q']],['BC',q,r,['q','r']],['AC',p,r,['p','r']]][pair];const area=Math.abs(a)*(q-p)*(r-q)*(r-p)/2,m=a*(u+v),b=-a*u*v;const wrongM=m!==0?-m:a*(v-u),wrongB=b!==0?-b:a,wrongArea=area*2;return {a,p,q,r,name,u,v,letters,m,b,answer:area,answered:false,options:shuffled([{m,b,area},{m:wrongM,b:wrongB,area},{m,b,area:wrongArea},{m:wrongM,b:wrongB,area:wrongArea}])};}
function begin(params){let a,p,q,r;if(params){({a,p,q,r}=params);}else{a=[.25,.5,1,2,3,-.25,-.5,-1,-2][ri(0,8)];p=ri(-5,0);q=p+ri(1,4);r=q+ri(1,4);}state=makeQuestion(a,p,q,r,ri(0,2));question++;render();}
function isCorrect(v){return v.m===state.m&&v.b===state.b&&v.area===state.answer;}
function render(){const {a,p,q,r,name,letters}=state;$('count').textContent='第'+question+'問';$('score').textContent='正解 '+hits+' 問 · 回答 '+attempts+' 問';$('equation').innerHTML='y = '+(a===1?'':a===-1?'−':frac(a))+'x²';$('question-title').innerHTML='直線 <em>'+name+'</em> の式と<br>三角形 <em>ABC</em> の面積は？';$('target-line').textContent='出題：直線 '+name;$('parameters').innerHTML=Object.entries({a,p,q,r}).map(([k,v])=>'<div class="parameter"><em>'+k+'</em><strong>'+frac(v)+'</strong></div>').join('');$('choices').innerHTML=state.options.map((v,i)=>'<button class="choice" data-i="'+i+'"><span class="key">'+(i+1)+'</span><span class="combination"><span class="choice-equation">'+lineEquation(v.m,v.b)+'</span><span class="choice-area">S = '+frac(v.area)+'</span></span></button>').join('');$('choices').querySelectorAll('button').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i)));$('feedback').innerHTML='<strong>直線の式と面積、両方を選ぶんだ！</strong><span>紫の直線 '+name+' に注目だぞ。</span>';$('formula').hidden=true;$('hint-toggle').setAttribute('aria-expanded','false');$('hint-toggle').innerHTML='2つの公式を見る <span>＋</span>';const [s,t]=letters;$('formula').innerHTML='<div class="math">'+name+'：y = a('+s+' + '+t+')x − a'+s+t+'</div><p>傾きは「a × 和」、切片は「−a × 積」</p><div class="math">S = '+frac(.5)+'|a|(q − p)(r − q)(r − p)</div><p>面積は「半分 × |a| × 3つの差」</p>';draw();}
function answer(i){if(state.answered||!Number.isInteger(i)||i<0||i>3)return;state.answered=true;attempts++;const good=isCorrect(state.options[i]);if(good)hits++;$('choices').querySelectorAll('button').forEach((b,j)=>{b.disabled=true;if(isCorrect(state.options[j]))b.classList.add('correct');else if(j===i)b.classList.add('wrong');});const {a,p,q,r,u,v,m,b,name,answer:ans}=state;const par=n=>'('+frac(n)+')';$('feedback').innerHTML='<strong>'+(good?'正解！ 両方できたな！':'おしい！ 緑の組み合わせが正解だぞ。')+'</strong><div class="explain-line">傾き：'+frac(a)+' × ('+frac(u)+' + '+par(v)+') = '+frac(m)+'<br>切片：−'+par(a)+' × '+par(u)+' × '+par(v)+' = '+frac(b)+'</div><div class="calculation">S = '+frac(.5)+' × '+frac(Math.abs(a))+' × '+(q-p)+' × '+(r-q)+' × '+(r-p)+' = '+frac(ans)+'</div>';$('score').textContent='正解 '+hits+' 問 · 回答 '+attempts+' 問';}
`+js.slice(end);
js=js.replace("+'</g>';for(const [name", "+line(lo,state.m*lo+state.b,hi,state.m*hi+state.b,'stroke=\"#9561ce\" stroke-width=\"3.5\"')+'</g>';for(const [name");
js=js.replace("'公式を見る <span>＋</span>'","'2つの公式を見る <span>＋</span>'");
js=js.replace("r:state.r,question","r:state.r,line:state.name,question");
fs.writeFileSync(file,js);
let html=fs.readFileSync('dist/index.html','utf8');
html=html.replace('放物線上の三角形の面積公式を覚えよう。','直線の式と三角形の面積の公式を覚えよう。').replace('<h2>三角形 ABC の<br>面積 <em>S</em> は？</h2>','<h2 id="question-title"></h2>').replace('AREA QUIZ','LINE & AREA QUIZ').replace('図の数値を使って、答えを選ぶんだ！','直線の式と面積の組み合わせを選ぼう。').replace('<span><i class="green"></i>線分 BD</span>','<span><i class="purple"></i><b id="target-line"></b></span>').replace('正解 0 / 0','正解 0 問 · 回答 0 問');
fs.writeFileSync('dist/index.html',html);
fs.appendFileSync('dist/style.css', '\n.workspace{grid-template-columns:minmax(0,1.3fr) minmax(410px,1fr)}.quiz-panel{position:relative;gap:12px;padding:22px}h2{font-size:25px;line-height:1.35;margin:8px 0}.choice{min-width:0;min-height:100px;padding:12px;gap:10px;font-size:22px}.combination{display:flex;flex-direction:column;gap:9px;font-family:Georgia,serif;min-width:0}.choice-equation{white-space:nowrap}.choice-area{font-size:21px;color:#647086}.choice.correct .choice-area{color:#15744f}.feedback{min-height:118px;gap:7px;padding:12px 14px}.feedback .explain-line{font-size:14px;line-height:1.8}.feedback .calculation{font-size:16px;gap:3px}.feedback .frac,.feedback .frac span{font-size:inherit;color:inherit}.purple{background:#9561ce}.legend b{font-weight:600}.hint{position:relative}#formula{position:absolute;bottom:35px;left:-6px;right:-6px;background:#fff;border:1px solid #cbd7e5;box-shadow:0 6px 24px #19294325;border-radius:12px;padding:14px;z-index:3}.math{font-size:18px}.next{min-height:44px}.hint button{padding:0}@media(min-width:901px) and (max-height:730px){.app{gap:10px;padding-top:10px}.quiz-panel{padding:16px;gap:9px}h2{font-size:22px}.choice{min-height:88px;padding:9px;font-size:21px}.feedback{min-height:108px;padding:9px 12px}.next{min-height:40px;padding:9px 16px}.hint{padding-top:8px}}@media(min-width:901px) and (max-width:1100px){.workspace{grid-template-columns:minmax(0,1fr) minmax(400px,1fr)}.quiz-panel{padding:16px}.choice{font-size:20px;gap:7px;padding:10px}.math{font-size:17px}}@media(max-width:900px){.workspace{grid-template-columns:1fr}}\n');
